### ISSUE TITLE
Error on commit style configuration

### ISSUE THREAD

**Issue by nfilzi** [diazgdev/git_auto#1]
Hi there!

Got an issue configuring the commit style.

```bash
git_auto config

⚙️  GitAuto Configuration
Choose an option: 🤖 Configure AI provider
Choose AI provider: OpenAI (GPT-4, GPT-3.5 Turbo)
✓ AI provider updated to openai

No API key found for OPENAI. Let's set it up.
Enter your API key: ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
✓ API key updated
Choose AI model: GPT-4o mini
✓ AI model updated to gpt-4o-mini
Choose an option: 💫 Configure commit style
Choose commit message style: Minimal (type: description)
/Users/nfilzi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/git_auto-0.2.0/lib/git_auto/commands/config_command.rb:159:in `configure_commit_style': undefined method `set' for an instance of GitAuto::Config::Settings (NoMethodError)

        @settings.set(:commit_style, style)
                 ^^^^
Did you mean?  get
	from /Users/nfilzi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/git_auto-0.2.0/lib/git_auto/commands/config_command.rb:82:in `block in interactive_config'
	from <internal:kernel>:187:in `loop'
	from /Users/nfilzi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/git_auto-0.2.0/lib/git_auto/commands/config_command.rb:68:in `interactive_config'
	from /Users/nfilzi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/git_auto-0.2.0/lib/git_auto/commands/config_command.rb:17:in `execute'
	from /Users/nfilzi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/git_auto-0.2.0/lib/git_auto/cli.rb:45:in `config'
	from /Users/nfilzi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /Users/nfilzi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/nfilzi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /Users/nfilzi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
	from /Users/nfilzi/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0/gems/git_auto-0.2.0/exe/git_auto:7:in `<top (required)>'
	from /Users/nfilzi/.rbenv/versions/3.3.6/bin/git_auto:25:in `load'
	from /Users/nfilzi/.rbenv/versions/3.3.6/bin/git_auto:25:in `<main>'
```

**Comment by diazgdev** [comment]
Hey @nfilzi !!

Thank you so much for reporting this issue. 
I've pushed a fix that resolves the issue (see commit 26a0c2b). 

Please let me know if you encounter any further problems. 

Closing this now
